"""Add credits tables

Revision ID: 05c9107b6ca2
Revises: b5ceb2ff04f9
Create Date: 2025-12-02 14:42:53.169931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c9107b6ca2'
down_revision: Union[str, Sequence[str], None] = 'b5ceb2ff04f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_credito', sa.String(length=50), nullable=False),
    sa.Column('asociado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_credito', sa.Enum('CONSUMO', 'VIVIENDA', 'VEHICULO', 'EDUCACION', 'MICROEMPRESA', 'CALAMIDAD', 'LIBRE_INVERSION', name='tipocredito'), nullable=False),
    sa.Column('monto_solicitado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_aprobado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monto_desembolsado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tasa_interes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('plazo_meses', sa.Integer(), nullable=False),
    sa.Column('modalidad_pago', sa.Enum('MENSUAL', 'QUINCENAL', 'SEMANAL', name='modalidadpago'), nullable=True),
    sa.Column('tipo_cuota', sa.Enum('FIJA', 'VARIABLE', name='tipocuota'), nullable=True),
    sa.Column('destino', sa.String(length=500), nullable=False),
    sa.Column('garantia', sa.Text(), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.Column('fecha_desembolso', sa.Date(), nullable=True),
    sa.Column('fecha_primer_pago', sa.Date(), nullable=True),
    sa.Column('fecha_ultimo_pago', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('SOLICITADO', 'EN_ESTUDIO', 'APROBADO', 'RECHAZADO', 'DESEMBOLSADO', 'AL_DIA', 'MORA', 'CANCELADO', 'CASTIGADO', name='estadocredito'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('valor_cuota', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_intereses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_a_pagar', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('saldo_capital', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('saldo_interes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('saldo_mora', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dias_mora', sa.Integer(), nullable=True),
    sa.Column('solicitado_por_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_por_id', sa.Integer(), nullable=True),
    sa.Column('desembolsado_por_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('asiento_desembolso_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['asiento_desembolso_id'], ['asientos_contables.id'], ),
    sa.ForeignKeyConstraint(['asociado_id'], ['asociados.id'], ),
    sa.ForeignKeyConstraint(['desembolsado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditos_asociado_id'), 'creditos', ['asociado_id'], unique=False)
    op.create_index(op.f('ix_creditos_id'), 'creditos', ['id'], unique=False)
    op.create_index(op.f('ix_creditos_numero_credito'), 'creditos', ['numero_credito'], unique=True)
    op.create_table('cuotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('valor_cuota', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_pagado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('dias_mora', sa.Integer(), nullable=True),
    sa.Column('valor_mora', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADA', 'MORA', 'REFINANCIADA', name='estadocuota'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuotas_credito_id'), 'cuotas', ['credito_id'], unique=False)
    op.create_index(op.f('ix_cuotas_fecha_vencimiento'), 'cuotas', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_cuotas_id'), 'cuotas', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('numero_recibo', sa.String(length=50), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_capital', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_interes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_mora', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_otros', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos_contables.id'], ),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_recibo')
    )
    op.create_index(op.f('ix_pagos_credito_id'), 'pagos', ['credito_id'], unique=False)
    op.create_index(op.f('ix_pagos_fecha_pago'), 'pagos', ['fecha_pago'], unique=False)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('abonos_cuotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('cuota_id', sa.Integer(), nullable=False),
    sa.Column('valor_abonado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cuota_id'], ['cuotas.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abonos_cuotas_id'), 'abonos_cuotas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abonos_cuotas_id'), table_name='abonos_cuotas')
    op.drop_table('abonos_cuotas')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_fecha_pago'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_credito_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_cuotas_id'), table_name='cuotas')
    op.drop_index(op.f('ix_cuotas_fecha_vencimiento'), table_name='cuotas')
    op.drop_index(op.f('ix_cuotas_credito_id'), table_name='cuotas')
    op.drop_table('cuotas')
    op.drop_index(op.f('ix_creditos_numero_credito'), table_name='creditos')
    op.drop_index(op.f('ix_creditos_id'), table_name='creditos')
    op.drop_index(op.f('ix_creditos_asociado_id'), table_name='creditos')
    op.drop_table('creditos')
    # ### end Alembic commands ###
