"""Add savings tables

Revision ID: 06ad0e83a371
Revises: 05c9107b6ca2
Create Date: 2025-12-02 15:05:23.737205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ad0e83a371'
down_revision: Union[str, Sequence[str], None] = '05c9107b6ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_ahorro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasa_ahorro_vista', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tasa_ahorro_programado', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tasa_cdat', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tasa_aportes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto_minimo_apertura', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_minimo_consignacion', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_minimo_cdat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gmf_activo', sa.Boolean(), nullable=True),
    sa.Column('tasa_gmf', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('cuota_manejo_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_ahorro_id'), 'configuracion_ahorro', ['id'], unique=False)
    op.create_table('cuentas_ahorro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=20), nullable=False),
    sa.Column('asociado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ahorro', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('saldo_disponible', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_bloqueado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tasa_interes_anual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cuota_manejo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meta_ahorro', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cuota_mensual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fecha_inicio_programado', sa.Date(), nullable=True),
    sa.Column('fecha_fin_programado', sa.Date(), nullable=True),
    sa.Column('plazo_dias', sa.Integer(), nullable=True),
    sa.Column('fecha_apertura_cdat', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento_cdat', sa.Date(), nullable=True),
    sa.Column('renovacion_automatica', sa.Boolean(), nullable=True),
    sa.Column('asiento_apertura_id', sa.Integer(), nullable=True),
    sa.Column('abierta_por_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['abierta_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['asiento_apertura_id'], ['asientos_contables.id'], ),
    sa.ForeignKeyConstraint(['asociado_id'], ['asociados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_ahorro_id'), 'cuentas_ahorro', ['id'], unique=False)
    op.create_index(op.f('ix_cuentas_ahorro_numero_cuenta'), 'cuentas_ahorro', ['numero_cuenta'], unique=True)
    op.create_table('movimientos_ahorro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_movimiento', sa.String(length=30), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_nuevo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('asiento_id', sa.Integer(), nullable=True),
    sa.Column('realizado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos_contables.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_ahorro.id'], ),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_ahorro_id'), 'movimientos_ahorro', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_ahorro_numero_movimiento'), 'movimientos_ahorro', ['numero_movimiento'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_ahorro_numero_movimiento'), table_name='movimientos_ahorro')
    op.drop_index(op.f('ix_movimientos_ahorro_id'), table_name='movimientos_ahorro')
    op.drop_table('movimientos_ahorro')
    op.drop_index(op.f('ix_cuentas_ahorro_numero_cuenta'), table_name='cuentas_ahorro')
    op.drop_index(op.f('ix_cuentas_ahorro_id'), table_name='cuentas_ahorro')
    op.drop_table('cuentas_ahorro')
    op.drop_index(op.f('ix_configuracion_ahorro_id'), table_name='configuracion_ahorro')
    op.drop_table('configuracion_ahorro')
    # ### end Alembic commands ###
