"""Agregar tabla documentos

Revision ID: 6370f656435b
Revises: 5e113ba4e336
Create Date: 2025-12-02 14:03:49.855782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6370f656435b'
down_revision: Union[str, Sequence[str], None] = '5e113ba4e336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asociado_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('nombre_almacenado', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('es_valido', sa.Boolean(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('validado_por_id', sa.Integer(), nullable=True),
    sa.Column('notas_validacion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asociado_id'], ['asociados.id'], ),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['validado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_almacenado')
    )
    op.create_index(op.f('ix_documentos_asociado_id'), 'documentos', ['asociado_id'], unique=False)
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_tipo_documento'), 'documentos', ['tipo_documento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_tipo_documento'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_asociado_id'), table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
