"""Add accounting tables

Revision ID: b5ceb2ff04f9
Revises: 6370f656435b
Create Date: 2025-12-02 14:25:21.814076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ceb2ff04f9'
down_revision: Union[str, Sequence[str], None] = '6370f656435b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas_contables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('ACTIVO', 'PASIVO', 'PATRIMONIO', 'INGRESO', 'GASTO', name='tipocuenta'), nullable=False),
    sa.Column('naturaleza', sa.Enum('DEBITO', 'CREDITO', name='naturalezacuenta'), nullable=False),
    sa.Column('cuenta_padre_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('es_auxiliar', sa.Boolean(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_padre_id'], ['cuentas_contables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_contables_codigo'), 'cuentas_contables', ['codigo'], unique=True)
    op.create_index(op.f('ix_cuentas_contables_id'), 'cuentas_contables', ['id'], unique=False)
    op.create_index(op.f('ix_cuentas_contables_tipo'), 'cuentas_contables', ['tipo'], unique=False)
    op.create_table('asientos_contables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('APORTE', 'RETIRO', 'PRESTAMO', 'PAGO_PRESTAMO', 'INTERES', 'AJUSTE', 'CIERRE', 'APERTURA', 'OTRO', name='tipomovimiento'), nullable=False),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('documento_referencia', sa.String(length=100), nullable=True),
    sa.Column('total_debito', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_credito', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cuadrado', sa.Boolean(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('fecha_anulacion', sa.DateTime(), nullable=True),
    sa.Column('anulado_por_id', sa.Integer(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['anulado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asientos_contables_fecha'), 'asientos_contables', ['fecha'], unique=False)
    op.create_index(op.f('ix_asientos_contables_id'), 'asientos_contables', ['id'], unique=False)
    op.create_index(op.f('ix_asientos_contables_numero'), 'asientos_contables', ['numero'], unique=True)
    op.create_index(op.f('ix_asientos_contables_tipo_movimiento'), 'asientos_contables', ['tipo_movimiento'], unique=False)
    op.create_table('aportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asociado_id', sa.Integer(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('numero_recibo', sa.String(length=50), nullable=True),
    sa.Column('tipo_aporte', sa.String(length=50), nullable=False),
    sa.Column('concepto', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos_contables.id'], ),
    sa.ForeignKeyConstraint(['asociado_id'], ['asociados.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aportes_asociado_id'), 'aportes', ['asociado_id'], unique=False)
    op.create_index(op.f('ix_aportes_fecha'), 'aportes', ['fecha'], unique=False)
    op.create_index(op.f('ix_aportes_id'), 'aportes', ['id'], unique=False)
    op.create_table('movimientos_contables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('debito', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credito', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('detalle', sa.String(length=500), nullable=True),
    sa.Column('tercero_tipo', sa.String(length=50), nullable=True),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos_contables.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_contables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_contables_asiento_id'), 'movimientos_contables', ['asiento_id'], unique=False)
    op.create_index(op.f('ix_movimientos_contables_cuenta_id'), 'movimientos_contables', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_movimientos_contables_id'), 'movimientos_contables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_contables_id'), table_name='movimientos_contables')
    op.drop_index(op.f('ix_movimientos_contables_cuenta_id'), table_name='movimientos_contables')
    op.drop_index(op.f('ix_movimientos_contables_asiento_id'), table_name='movimientos_contables')
    op.drop_table('movimientos_contables')
    op.drop_index(op.f('ix_aportes_id'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_fecha'), table_name='aportes')
    op.drop_index(op.f('ix_aportes_asociado_id'), table_name='aportes')
    op.drop_table('aportes')
    op.drop_index(op.f('ix_asientos_contables_tipo_movimiento'), table_name='asientos_contables')
    op.drop_index(op.f('ix_asientos_contables_numero'), table_name='asientos_contables')
    op.drop_index(op.f('ix_asientos_contables_id'), table_name='asientos_contables')
    op.drop_index(op.f('ix_asientos_contables_fecha'), table_name='asientos_contables')
    op.drop_table('asientos_contables')
    op.drop_index(op.f('ix_cuentas_contables_tipo'), table_name='cuentas_contables')
    op.drop_index(op.f('ix_cuentas_contables_id'), table_name='cuentas_contables')
    op.drop_index(op.f('ix_cuentas_contables_codigo'), table_name='cuentas_contables')
    op.drop_table('cuentas_contables')
    # ### end Alembic commands ###
