"""add fecha_ultimo_interes to cuentas_ahorro

Revision ID: bea13a3fdb87
Revises: 06ad0e83a371
Create Date: 2025-12-05 23:36:22.110312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea13a3fdb87'
down_revision: Union[str, Sequence[str], None] = '06ad0e83a371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas_ahorro', sa.Column('fecha_ultimo_interes', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas_ahorro', 'fecha_ultimo_interes')
    # ### end Alembic commands ###
