"""Initial migration with users and associates

Revision ID: da0ca03f5df4
Revises: 
Create Date: 2025-12-02 12:52:24.174343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0ca03f5df4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=30), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('correo_electronico', sa.String(length=200), nullable=False),
    sa.Column('telefono_principal', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('hoja_vida_url', sa.String(length=500), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('datos_personales', sa.Text(), nullable=True),
    sa.Column('datos_laborales', sa.Text(), nullable=True),
    sa.Column('informacion_familiar', sa.Text(), nullable=True),
    sa.Column('informacion_financiera', sa.Text(), nullable=True),
    sa.Column('informacion_academica', sa.Text(), nullable=True),
    sa.Column('informacion_vivienda', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asociados_id'), 'asociados', ['id'], unique=False)
    op.create_index(op.f('ix_asociados_numero_documento'), 'asociados', ['numero_documento'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_asociados_numero_documento'), table_name='asociados')
    op.drop_index(op.f('ix_asociados_id'), table_name='asociados')
    op.drop_table('asociados')
    # ### end Alembic commands ###
